#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'internal-messages.pb'; rescue LoadError; end
begin; require 'iwsn-messages.pb'; rescue LoadError; end

module De
  module Uniluebeck
    module Itm
      module Tr
        module Iwsn
          module Messages
            # forward declarations
            class ExternalPluginMessage < ::ProtocolBuffers::Message; end

            class ExternalPluginMessage < ::ProtocolBuffers::Message
              # forward declarations

              # enums
              module Type
                include ::ProtocolBuffers::Enum

                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ExternalPluginMessage.Type"

                INTERNAL_MESSAGE = 1
                IWSN_MESSAGE = 2
              end

              set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ExternalPluginMessage"

              required ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ExternalPluginMessage::Type, :type, 1
              optional ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::InternalMessage, :internal_message, 101
              optional ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::Message, :iwsn_message, 102
            end

          end
        end
      end
    end
  end
end
