#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module De
  module Uniluebeck
    module Itm
      module Tr
        module Iwsn
          module Messages
            # forward declarations
            class ReservationEvent < ::ProtocolBuffers::Message; end
            class InternalMessage < ::ProtocolBuffers::Message; end

            class ReservationEvent < ::ProtocolBuffers::Message
              # forward declarations
              class SecretReservationKey < ::ProtocolBuffers::Message; end

              # enums
              module Type
                include ::ProtocolBuffers::Enum

                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ReservationEvent.Type"

                STARTED = 1
                ENDED = 2
              end

              set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ReservationEvent"

              # nested messages
              class SecretReservationKey < ::ProtocolBuffers::Message
                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ReservationEvent.SecretReservationKey"

                required :string, :nodeUrnPrefix, 1
                required :string, :username, 2
                required :string, :key, 3
              end

              required ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ReservationEvent::Type, :type, 1
              repeated ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ReservationEvent::SecretReservationKey, :secretReservationKeys, 2
              repeated :string, :nodeUrns, 3
              required :string, :interval_start, 4
              required :string, :interval_end, 5
            end

            class InternalMessage < ::ProtocolBuffers::Message
              # forward declarations

              # enums
              module Type
                include ::ProtocolBuffers::Enum

                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.InternalMessage.Type"

                RESERVATION_EVENT = 1
              end

              set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.InternalMessage"

              required ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::InternalMessage::Type, :type, 1
              optional ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ReservationEvent, :reservationEvent, 101
            end

          end
        end
      end
    end
  end
end
