#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module De
  module Uniluebeck
    module Itm
      module Tr
        module Iwsn
          module Messages
            # forward declarations
            class ReservationEvent < ::ProtocolBuffers::Message; end
            class InternalMessage < ::ProtocolBuffers::Message; end

            class ReservationEvent < ::ProtocolBuffers::Message
              # forward declarations

              # enums
              module Type
                include ::ProtocolBuffers::Enum

                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ReservationEvent.Type"

                STARTED = 1
                ENDED = 2
              end

              set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.ReservationEvent"

              required ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ReservationEvent::Type, :type, 1
              required :string, :key, 2
              required :string, :username, 3
              repeated :string, :nodeUrns, 4
              required :string, :interval_start, 5
              required :string, :interval_end, 6
            end

            class InternalMessage < ::ProtocolBuffers::Message
              # forward declarations

              # enums
              module Type
                include ::ProtocolBuffers::Enum

                set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.InternalMessage.Type"

                RESERVATION_EVENT = 1
              end

              set_fully_qualified_name "de.uniluebeck.itm.tr.iwsn.messages.InternalMessage"

              required ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::InternalMessage::Type, :type, 1
              optional ::De::Uniluebeck::Itm::Tr::Iwsn::Messages::ReservationEvent, :reservationEvent, 101
            end

          end
        end
      end
    end
  end
end
